apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: site-magicnonsense
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
    - host: magic-nonsense.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: site-magicnonsense
                port: { name: http }
            pathType: Prefix
  tls:
    - hosts: [magic-nonsense.com]
      secretName: site-magicnonsense-cert
