apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: magicnonsense-public

commonLabels:
  app.kubernetes.io/name: site-magicnonsense

images:
  - { name: ghcr.io/strootje/site-magicnonsense, newTag: main }

resources:
  - deployment.yml
  - ingress.yml
  - service.yml
